# Generated by Django 5.2.16 on 2026-08-03 09:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tcg_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=20)),
                ("rarity", models.CharField(blank=True, default="", max_length=50)),
                ("hp", models.CharField(blank=True, default="", max_length=10)),
                ("supertype", models.CharField(max_length=20)),
                ("language", models.CharField(default="en", max_length=5)),
                ("image_small", models.URLField(max_length=255)),
                ("image_large", models.URLField(max_length=255)),
                ("artist", models.CharField(blank=True, default="", max_length=255)),
                (
                    "national_pokedex_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "subtypes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "evolves_from",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "evolves_to",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "tcgplayer_url",
                    models.URLField(blank=True, default="", max_length=255),
                ),
                (
                    "cardmarket_url",
                    models.URLField(blank=True, default="", max_length=255),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tcg_id", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("series", models.CharField(max_length=100)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=5)),
                ("imported", models.BooleanField(default=False)),
                (
                    "image_symbol",
                    models.URLField(blank=True, default="", max_length=255),
                ),
                ("image_logo", models.URLField(blank=True, default="", max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Attack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cost", models.JSONField(blank=True, default=list)),
                (
                    "converted_energy_cost",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("damage", models.CharField(blank=True, default="", max_length=20)),
                ("text", models.TextField(blank=True, default="")),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacks",
                        to="cards.card",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="card",
            name="set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cards",
                to="cards.set",
            ),
        ),
        migrations.CreateModel(
            name="Resistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=10)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resistances",
                        to="cards.card",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resistance_entries",
                        to="cards.type",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="types",
            field=models.ManyToManyField(
                blank=True, related_name="cards", to="cards.type"
            ),
        ),
        migrations.CreateModel(
            name="Weakness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=10)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weaknesses",
                        to="cards.card",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weakness_entries",
                        to="cards.type",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["name"], name="cards_card_name_a125cc_idx"),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["rarity"], name="cards_card_rarity_0cc733_idx"),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["supertype"], name="cards_card_superty_518f56_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.UniqueConstraint(
                fields=("set", "number", "language"),
                name="unique_card_set_number_language",
            ),
        ),
    ]
