# Generated by Django 5.2.16 on 2026-08-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="card",
            name="unique_card_set_number_language",
        ),
    ]
