# Generated by Django 5.2.16 on 2026-10-01 03:39

from django.db import migrations, models
from unidecode import unidecode


def backfill_name_ascii(apps, schema_editor):
    # Every Card synced before this migration has name_ascii="" (the field's
    # default) — Card.save() only starts computing it going forward. Without
    # this backfill, accent-insensitive search would silently fail for the
    # entire existing catalog until the next full re-sync. bulk_update in
    # batches rather than per-row .save(), since there's no need to re-run
    # save()'s own logic (it would just recompute the same value) and this
    # can be thousands of rows.
    Card = apps.get_model("cards", "Card")
    cards = list(Card.objects.all())
    for card in cards:
        card.name_ascii = unidecode(card.name)
    Card.objects.bulk_update(cards, ["name_ascii"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_remove_card_unique_card_set_number_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="name_ascii",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(backfill_name_ascii, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["name_ascii"], name="cards_card_name_as_ffbd4c_idx"
            ),
        ),
    ]
