# Generated by Django 5.2.16 on 2026-10-01 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0003_card_name_ascii"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HoroscopePull",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pull_date", models.DateField()),
                ("pulled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horoscope_pulls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-pulled_at"],
            },
        ),
        migrations.CreateModel(
            name="HoroscopeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supertype", models.CharField(max_length=20)),
                (
                    "rarity_tier",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("mid", "Mid"),
                            ("chase", "Chase"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horoscope_appearances",
                        to="cards.card",
                    ),
                ),
                (
                    "pull",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="horoscope.horoscopepull",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="horoscopepull",
            constraint=models.UniqueConstraint(
                fields=("user", "pull_date"),
                name="unique_horoscope_pull_per_user_per_day",
            ),
        ),
    ]
